version: "3.6"
services:
  vpn-proxy:
    container_name: vpn-proxy
    image: jeroenslot/nordvpn-proxy:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 103.86.96.100
      - 103.86.99.100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ovpn-data:/app/ovpn/config
    environment:
      - USERNAME= #REMOVED
      - PASSWORD= #REMOVED
      - LOCAL_NETWORK=192.168.88.0/24
      - COUNTRY=NL
      - PROTOCOL=udp
    networks:
      - default
    ports:
      - 8118:8118 #Privoxy PROXY
      - 8989:8989 #Sonarr PVR tvshows
      - 7878:7878 #Radarr PVR movies
      - 9117:9117 #Jackett SEARCHPROVIDER
      - 6789:6789 #NZBget DOWNLOADER
      - 9091:9091 #Transmission DOWNLOADER
      - 51413:51413 #p2p
      - 51413:51413/udp #p2p DHT
    restart: always
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    environment:
      - TZ=${TZ}
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
  organizr:
    container_name: organizr
    image: lsiocommunity/organizr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/organizr:/config
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "80:80"
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=022 #optional
    volumes:
      - ${USERDIR}/docker/jellyfin/config:/config
      - ${USERDIR}/Media/TVshows:/data/tvshows
      - ${USERDIR}/Media/Movies:/data/movies
      - ${USERDIR}/Music:/data/music
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices:
      - /dev/dri:/dev/dri #intel Hardware Acceleration
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=admin
      - PASS= #REMOVED
    volumes:
      - ${USERDIR}/docker/transmission/config:/config
      - ${USERDIR}/Downloads/incoming:/downloads
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/sonarr/config:/config
      - ${USERDIR}/Downloads/incoming:/downloads
      - ${USERDIR}/Media/TVshows:/tv
#    ports:
#      - 8989:8989
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/jackett/config:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/Downloads/incoming:/downloads 
#    ports:
#      - 9117:9117
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/radarr:/config
      - ${USERDIR}/Downloads/incoming:/downloads
      - ${USERDIR}/Media/Movies:/movies
#    ports:
#      - 7878:7878
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/nzbget/config:/config
      - ${USERDIR}/Downloads/incoming:/downloads
#    ports:
#      - 6789:6789
volumes:
  ovpn-data:
