version: "2.0"
services:
# ____________________ Portainer [SERVER/docker-management]
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    environment:
      - TZ=${TZ}
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
# ____________________ PiHole [SECURITY/recursive-DNS]
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      DNS-network:
        ipv4_address: 192.168.88.2
    environment:
      ServerIP: 192.168.88.2
      WEBPASSWORD: "TVflix!56"
      PHP_ENV_CONFIG: "/etc/lighttpd/conf-enabled/15-fastcgi-php.conf"
      TZ: ${TZ}
      DNS1: 192.168.88.3#53
    volumes:
      - ${USERDIR}/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - ${USERDIR}/docker/pihole:/etc/pihole:rw
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/pihole/var-log/pihole.log:/var/log/pihole.log
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    dns:
      - 127.0.0.1
      - 192.168.88.3#53
# ____________________ Unbound [SECURITY/ads-aware-dns-server]
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    restart: always
    mac_address: d0:ca:ab:cd:ef:02
    networks:
      DNS-network:
        ipv4_address: 192.168.88.3
#    volumes:
#      - ${USERDIR}/docker/unbound:/opt/unbound/etc/unbound/
    ports:
      - 53/tcp
      - 53/udp
# ____________________ Unifi Controller [HOME/Wifi]
  unifi:
    container_name: unifi
    image: goofball222/unifi
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/unifi/cert:/usr/lib/unifi/cert
      - ${USERDIR}/docker/unifi/data:/usr/lib/unifi/data
      - ${USERDIR}/docker/unifi/logs:/usr/lib/unifi/logs
# ____________________ SyncThing [CLOUD/filesync]
  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${USERDIR}/docker/syncthing/config:/config
      - ${USERDIR}/Documents:/documents:rw
      - ${USERDIR}/Pictures:/photos:rw
      - /mnt/pool/backups:/backups:rw
    ports:
      - '8384:8384'
      - '21027:21027/udp'
      - '22000:22000'
# ____________________ 
# _________TBA________ SeaFile [CLOUD/SeaFile]
# _________TBA________ Firefox [CLOUD/SeaFile]
# _________TBA________ Piwigo or OwnPhotos [CLOUD/photo-library]
# ____________________ 
# ____________________ Jellyfin [MEDIA/library]
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UMASK_SET=022 #optional
    volumes:
      - ${USERDIR}/docker/jellyfin/config:/config
      - ${USERDIR}/Media/TVshows:/data/tvshows
      - ${USERDIR}/Media/Movies:/data/movies
      - ${USERDIR}/Music:/data/music
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices:
      - /dev/dri:/dev/dri
# ____________________ vpn-proxy [MEDIA/vpn-client-for-media]
  vpn-proxy:
    container_name: vpn-proxy
    image: jeroenslot/nordvpn-proxy:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 103.86.96.100
      - 103.86.99.100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ovpn-data:/app/ovpn/config
    environment:
      - USERNAME=zilexa@gmx.com
      - PASSWORD=TVflix!56
      - LOCAL_NETWORK=192.168.88.0/24
      - COUNTRY=NL
      - PROTOCOL=udp
    networks:
      - default
    ports:
      - 8118:8118 #Privoxy
      - 8989:8989 #Sonarr
      - 7878:7878 #Radarr
      - 9117:9117 #Jackett
      - 6789:6789 #NZBget
      - 9091:9091 #Transmission
      - 6767:6767 #Subtitles
      - 51413:51413 #p2p
      - 51413:51413/udp #p2p DHT
    restart: always
# ____________________ Transmission [MEDIA/download-client]
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Amsterdam
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
      - USER=admin
      - PASS=TVflix!56
    volumes:
      - ${USERDIR}/docker/transmission/config:/config
      - ${USERDIR}/Media:/media
      - ${USERDIR}/Media/incoming/blackhole:/watch
# ____________________ NZBget [MEDIA/download-client]
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/nzbget/config:/config
      - ${USERDIR}/Media:/media
#    ports:
#      - 6789:6789
# ____________________ Sonarr [MEDIA/PVR-TVshows]
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/sonarr/config:/config
      - ${USERDIR}/Media:/media
#    ports:
#      - 8989:8989
# ____________________ Jackett [MEDIA/torrent-proxy for Sonarr&Radarr]
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/jackett/config:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/Media:/media 
#    ports:
#      - 9117:9117
# ____________________ Radarr [MEDIA/PVR-Movies]
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/radarr/config:/config
      - ${USERDIR}/Media:/media
#    ports:
#      - 7878:7878
# ____________________ Bazarr [MEDIA/subtitle-proxy for Sonarr&Radarr]
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    network_mode: service:vpn-proxy
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${USERDIR}/docker/bazarr/config:/config
      - ${USERDIR}/Media:/media
volumes:
  ovpn-data:
networks:
  DNS-network:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: 192.168.88.0/24
          gateway: 192.168.88.1
          ip_range: 192.168.88.2/31
