# ____________________ PiHole [SECURITY/recursive-DNS]
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      DNS-network:
        ipv4_address: 192.168.88.2
    environment:
      ServerIP: 192.168.88.2
      WEBPASSWORD: "TVflix!56"
      PHP_ENV_CONFIG: "/etc/lighttpd/conf-enabled/15-fastcgi-php.conf"
      TZ: ${TZ}
      DNS1: 192.168.88.3#53
      DNS2: 1.1.1.1
    volumes:
      - ${USERDIR}/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - ${USERDIR}/docker/pihole:/etc/pihole:rw
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/pihole/var-log/pihole.log:/var/log/pihole.log
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    dns:
      - 127.0.0.1
      - 192.168.88.3#53
# ____________________ Unbound [SECURITY/ads-aware-dns-server]
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    restart: always
    mac_address: d0:ca:ab:cd:ef:02
    networks:
      DNS-network:
        ipv4_address: 192.168.88.3
#    volumes:
#      - ${USERDIR}/docker/unbound:/opt/unbound/etc/unbound/
    ports:
      - 53/tcp
      - 53/udp
networks:
  DNS-network:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: 192.168.88.0/24
          gateway: 192.168.88.1
          ip_range: 192.168.88.2/31
