# ____________________ PiHole [SECURITY/recursive-DNS]
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      DNS-network:
        ipv4_address: 192.168.88.2
    environment:
      ServerIP: 192.168.88.2
      WEBPASSWORD: "R E M O V E D"
      PHP_ENV_CONFIG: "/etc/lighttpd/conf-enabled/15-fastcgi-php.conf"
      TZ: ${TZ}
    volumes:
      - ${USERDIR}/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - ${USERDIR}/docker/pihole:/etc/pihole:rw
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/pihole/var-log/pihole.log:/var/log/pihole.log
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    dns:
      - 127.0.0.1
      - 192.168.88.3
# ____________________ Unbound [SECURITY/ads-aware-dns-server]
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    restart: always
    mac_address: d0:ca:ab:cd:ef:02
    networks:
      DNS-network:
        ipv4_address: 192.168.88.3
#                                   ISSUE: it does not work when mounting:
#    volumes:
#      - ${USERDIR}/docker/unbound:/opt/unbound/etc/unbound/
    ports:
      - 53/tcp
      - 53/udp
