version: "2.0"
services:  
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    restart: always
    hostname: unbound
    domainname: ServerPC
    mac_address: 5a:58:dd:5c:f1:d5
    networks:
      MikroTik:
        ipv4_address: 192.168.88.3
    environment:
      ServerIP: 192.168.88.3       
      VIRTUAL_HOST: unbound.ServerPC  
      TZ: ${TZ}
    volumes:
      - ${USERDIR}/docker/unbound/config:/opt/unbound/etc/unbound/
    ports:
      - 53/tcp
      - 53/udp
# ____________________ PiHole [SECURITY/ads-aware-dns-server]
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    hostname: pihole
    domainname: ServerPC            
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    networks:
      MikroTik:
        ipv4_address: 192.168.88.2  
    environment:
      ServerIP: 192.168.88.2         
      VIRTUAL_HOST: pihole.ServerPC  
      WEBPASSWORD: "removed"                 
      PHP_ENV_CONFIG: "/etc/lighttpd/conf-enabled/15-fastcgi-php.conf"
      TZ: ${TZ}
    volumes:
      - ${USERDIR}/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - ${USERDIR}/docker/pihole:/etc/pihole:rw
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/pihole/var-log/pihole.log:/var/log/pihole.log
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    dns:
      - 127.0.0.1
      - 8.8.8.8
networks:
  MikroTik:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: 192.168.88.0/24          # <-- Update
          gateway: 192.168.88.1            # <-- Update
          ip_range: 192.168.88.192/28        # <-- Update
